# Generated by Django 2.1.7 on 2019-03-19 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('title', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('link', models.URLField()),
                ('description', models.TextField(null=True)),
                ('language', models.CharField(max_length=10)),
                ('lastBuildDate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('title', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('link', models.URLField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('language', models.CharField(max_length=10)),
                ('pubDate', models.CharField(max_length=100)),
                ('guid', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Channel')),
            ],
        ),
    ]
