# Generated by Django 2.1.7 on 2019-04-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField(primary_key=True, serialize=False)),
                ('image', models.TextField()),
                ('description', models.TextField()),
                ('pubDate', models.DateTimeField()),
                ('rss', models.TextField()),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('title', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('link', models.URLField()),
                ('description', models.TextField(null=True)),
                ('language', models.CharField(max_length=10)),
            ],
        ),
    ]
