# Generated by Django 2.1.7 on 2019-03-22 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('title', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('link', models.URLField()),
                ('description', models.TextField(null=True)),
                ('language', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('link', models.URLField()),
                ('image', models.TextField(null=True)),
                ('description', models.TextField()),
                ('pubDate', models.DateTimeField(null=True)),
                ('rss', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Channel')),
            ],
        ),
    ]
