# Generated by Django 2.1.7 on 2019-03-19 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_item_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
