# Generated by Django 2.1.7 on 2019-03-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190321_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rss',
            field=models.TextField(),
        ),
    ]
